### nnumpy -- is libray or package which deals with matrix and numpy handel multidimension array
### 1d array
 ### 2d array
### 3d/nd array ###


In [1]:
import numpy as np 

In [2]:
np.__version__

'2.1.3'

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
np.arange(20,10) #first arg is always less the second arg

array([], dtype=int64)

In [11]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [12]:
np.zeros(5)#parameter tunning

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5,dtype=int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [14]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.array(2,10)-- (row , columns)

In [16]:
np.zeros([10,10],dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones(2)

array([1., 1.])

In [18]:
np.ones(2,dtype=int)

array([1, 1])

In [19]:
np.ones([4,5,])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
random.rand(3,2) 


NameError: name 'random' is not defined

In [21]:
np.random.rand(3,2)

array([[0.25582229, 0.97413696],
       [0.9709698 , 0.75456299],
       [0.04423216, 0.31669562]])

In [22]:
np.random.rand(3)

array([0.45448245, 0.3364731 , 0.17512411])

In [23]:
np.random.randint(4,6)

4

In [24]:
np.random.randint(0,10)

2

In [25]:
np.random.randint(0,10,4)

array([0, 1, 2, 5], dtype=int32)

In [26]:
np.random.randint(0,10,5)

array([7, 2, 9, 6, 8], dtype=int32)

In [27]:
np.random.randint(10,20,4)

array([13, 11, 10, 17], dtype=int32)

In [28]:
n = np.random.randint(10,40,(8,10))
n

array([[35, 29, 32, 28, 22, 31, 29, 30, 22, 31],
       [37, 13, 37, 33, 34, 19, 29, 11, 21, 33],
       [25, 20, 30, 38, 16, 32, 15, 10, 17, 14],
       [36, 12, 22, 15, 26, 14, 19, 16, 32, 10],
       [38, 28, 26, 15, 29, 20, 30, 37, 38, 17],
       [15, 35, 27, 13, 15, 36, 21, 19, 22, 35],
       [19, 21, 35, 13, 37, 25, 17, 10, 18, 13],
       [28, 36, 27, 14, 11, 10, 31, 38, 12, 23]], dtype=int32)

In [29]:
n[0]

array([35, 29, 32, 28, 22, 31, 29, 30, 22, 31], dtype=int32)

In [30]:
n[5]

array([15, 35, 27, 13, 15, 36, 21, 19, 22, 35], dtype=int32)

In [31]:
n[0:6]

array([[35, 29, 32, 28, 22, 31, 29, 30, 22, 31],
       [37, 13, 37, 33, 34, 19, 29, 11, 21, 33],
       [25, 20, 30, 38, 16, 32, 15, 10, 17, 14],
       [36, 12, 22, 15, 26, 14, 19, 16, 32, 10],
       [38, 28, 26, 15, 29, 20, 30, 37, 38, 17],
       [15, 35, 27, 13, 15, 36, 21, 19, 22, 35]], dtype=int32)

In [32]:
n

array([[35, 29, 32, 28, 22, 31, 29, 30, 22, 31],
       [37, 13, 37, 33, 34, 19, 29, 11, 21, 33],
       [25, 20, 30, 38, 16, 32, 15, 10, 17, 14],
       [36, 12, 22, 15, 26, 14, 19, 16, 32, 10],
       [38, 28, 26, 15, 29, 20, 30, 37, 38, 17],
       [15, 35, 27, 13, 15, 36, 21, 19, 22, 35],
       [19, 21, 35, 13, 37, 25, 17, 10, 18, 13],
       [28, 36, 27, 14, 11, 10, 31, 38, 12, 23]], dtype=int32)

In [33]:
n[2:-1]

array([[25, 20, 30, 38, 16, 32, 15, 10, 17, 14],
       [36, 12, 22, 15, 26, 14, 19, 16, 32, 10],
       [38, 28, 26, 15, 29, 20, 30, 37, 38, 17],
       [15, 35, 27, 13, 15, 36, 21, 19, 22, 35],
       [19, 21, 35, 13, 37, 25, 17, 10, 18, 13]], dtype=int32)

In [34]:
n[::-1]

array([[28, 36, 27, 14, 11, 10, 31, 38, 12, 23],
       [19, 21, 35, 13, 37, 25, 17, 10, 18, 13],
       [15, 35, 27, 13, 15, 36, 21, 19, 22, 35],
       [38, 28, 26, 15, 29, 20, 30, 37, 38, 17],
       [36, 12, 22, 15, 26, 14, 19, 16, 32, 10],
       [25, 20, 30, 38, 16, 32, 15, 10, 17, 14],
       [37, 13, 37, 33, 34, 19, 29, 11, 21, 33],
       [35, 29, 32, 28, 22, 31, 29, 30, 22, 31]], dtype=int32)

In [35]:
n[::1]

array([[35, 29, 32, 28, 22, 31, 29, 30, 22, 31],
       [37, 13, 37, 33, 34, 19, 29, 11, 21, 33],
       [25, 20, 30, 38, 16, 32, 15, 10, 17, 14],
       [36, 12, 22, 15, 26, 14, 19, 16, 32, 10],
       [38, 28, 26, 15, 29, 20, 30, 37, 38, 17],
       [15, 35, 27, 13, 15, 36, 21, 19, 22, 35],
       [19, 21, 35, 13, 37, 25, 17, 10, 18, 13],
       [28, 36, 27, 14, 11, 10, 31, 38, 12, 23]], dtype=int32)

In [36]:
n[::2]

array([[35, 29, 32, 28, 22, 31, 29, 30, 22, 31],
       [25, 20, 30, 38, 16, 32, 15, 10, 17, 14],
       [38, 28, 26, 15, 29, 20, 30, 37, 38, 17],
       [19, 21, 35, 13, 37, 25, 17, 10, 18, 13]], dtype=int32)

In [37]:
n[0]

array([35, 29, 32, 28, 22, 31, 29, 30, 22, 31], dtype=int32)

In [38]:
n[0,5]

np.int32(31)

In [39]:
n[0:5]

array([[35, 29, 32, 28, 22, 31, 29, 30, 22, 31],
       [37, 13, 37, 33, 34, 19, 29, 11, 21, 33],
       [25, 20, 30, 38, 16, 32, 15, 10, 17, 14],
       [36, 12, 22, 15, 26, 14, 19, 16, 32, 10],
       [38, 28, 26, 15, 29, 20, 30, 37, 38, 17]], dtype=int32)

In [40]:
n[5,-3]

np.int32(19)

In [41]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [43]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [45]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [46]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

 ##  Second class of numpy (12th agu 2025)

In [50]:
mat= np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
row = 4
col= 5


In [54]:
col

5

In [55]:
row

4

In [57]:
a=mat[row,col]

np.int64(45)

In [60]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [61]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [62]:
mat[:,col]#how to print colunm info

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [63]:
mat[col]#how to print rows

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [64]:
mat[5]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [68]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [67]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [69]:
row

4

In [70]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [71]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
mat[row]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [74]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [75]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [76]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [77]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [78]:
mat[1:2,2:4]

array([[12, 13]])

In [79]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

# Masking

In [80]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [81]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [82]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [83]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [84]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])